#!/bin/bash

ROOT=`pwd`

ln -snf $ROOT/src/common    ./node_modules/common
ln -snf $ROOT/src/data      ./node_modules/data
ln -snf $ROOT/src/events    ./node_modules/events
ln -snf $ROOT/src/messaging ./node_modules/messaging
ln -snf $ROOT/src/ui        ./node_modules/ui
